---

- name: Install consul package
  ansible.builtin.package:
    name: consul
    state: present

# At this point we deploy the server config.
- name: Copy consul server configuration
  ansible.builtin.template:
    src: templates/consul-server.json
    dest: /etc/consul.d/server.json
    mode: 0644
  when: "'{{ consul_group }}' in group_names"
  tags:
    - config

# At this point we deploy the client config.
- name: Copy consul client configuration
  ansible.builtin.template:
    src: templates/consul-client.json
    dest: /etc/consul.d/client.json
    mode: 0644
  when: "'{{ consul_group }}' not in group_names"
  tags:
    - config

- name: Copy consul-server.service file
  ansible.builtin.copy:
    src: files/consul.service
    dest: /etc/systemd/system/consul.service
    mode: 0644

- name: Systemctl daemon-reload / start consul
  ansible.builtin.systemd:
    daemon_reload: true
    name: consul
    state: restarted
    enabled: true
