---

- name: Install etcd package
  package:
    name: etcd-server
    state: present
  when: ((ansible_distribution_release != "stretch") and (ansible_distribution_release != "xenial"))

- name: Install etcd package
  package:
    name: etcd
    state: present
  when: (ansible_distribution_release == "xenial")

- name: Setup snapshot repository
  apt_repository:
    repo: 'deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/20161015T102332Z/ testing main'
    filename: 'snapshot'
    update_cache: true
  when: (ansible_distribution_release == "stretch")

- name: Install etcd package
  package:
    name: etcd=2.3.7+dfsg-5
    state: present
  when: (ansible_distribution_release == "stretch")

- name: Set member name
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_NAME=\"{{ ansible_hostname }}\""
    regexp: ".*ETCD_NAME.*"
  tags:
    - config

- name: Set data directory
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_DATA_DIR=\"/var/lib/etcd/patroni\""
    regexp: ".*ETCD_DATA_DIR.*"
  tags:
    - config

- name: Listen for other cluster peers
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_LISTEN_PEER_URLS=\"http://{{ hostvars[ansible_hostname]['ansible_eth0']['ipv4']['address'] }}:2380\""
    regexp: ".*ETCD_LISTEN_PEER_URLS.*"
  tags:
    - config

- name: Setup advertised peer communication URL
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_INITIAL_ADVERTISE_PEER_URLS=\"http://{{ hostvars[ansible_hostname]['ansible_eth0']['ipv4']['address'] }}:2380\""
    regexp: ".*ETCD_INITIAL_ADVERTISE_PEER_URLS.*"
  tags:
    - config

- name: Enable client listen interface
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_LISTEN_CLIENT_URLS=\"http://localhost:2379,http://{{ hostvars[ansible_hostname]['ansible_eth0']['ipv4']['address'] }}:2379\""
    regexp: ".*ETCD_LISTEN_CLIENT_URLS.*"
  tags:
    - config

- name: Advertise client interface
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_ADVERTISE_CLIENT_URLS=\"{% for ip in dcs_ips %}http://{{ ip }}:2379{% if not loop.last %},{% endif %}{% endfor %}\""
    regexp: ".*ETCD_ADVERTISE_CLIENT_URLS.*"
  tags:
    - config

- name: Setup URLs of initials members
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_INITIAL_CLUSTER=\"{% for host in groups['dcs_servers'] %}{{ host }}=http://{{ hostvars[host]['ansible_eth0']['ipv4']['address'] }}:2380{% if not loop.last %},{% endif %}{% endfor %}\""
    regexp: ".*ETCD_INITIAL_CLUSTER.*"
  tags:
    - config

- name: systemctl daemon-reload / start etcd
  systemd:
    daemon_reload: true
    name: etcd
    state: restarted
    enabled: true
