---

- name: Set fact dcs_ips
  ansible.builtin.set_fact:
    dcs_ips: "{{ dcs_server_ips | default([hostvars[item]['ansible_eth0']['ipv4']['address']]) }}"
  with_items: "{{ groups['dcs_servers'] }}"
