---

- name: Set fact pgsql_server_ips
  ansible.builtin.set_fact:
    pgsql_server_ips: "{{ pgsql_server_ips | default([]) + [hostvars[item]['ansible_eth0']['ipv4']['address']] }}"
  with_items: "{{ groups['pgsql_servers'] }}"
