---

- name: Setup backports repository
  ansible.builtin.apt_repository:
    repo: 'deb http://ftp.debian.org/debian stretch-backports main'
    filename: 'backports'
    update_cache: true
  when: (ansible_distribution_release == "stretch")

- name: Install systemd from backports
  ansible.builtin.apt:
    name: systemd
    default_release: stretch-backports
    state: latest
  when: (ansible_distribution_release == "stretch")

- name: Systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
